name: Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-project:
    name: Check Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Configure Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: ERRORS_ENABLE_TESTS=ON
          run-build: false

      - name: Check Format
        run: |
          cmake --build build --target format-all
          git diff --exit-code HEAD
